artipie/go-adapter

README.md, pom.xml, src/main/java/com/yegor256/goproxy/Goproxy.java, src/test/java/com/yegor256/goproxy/GoproxyITCase.java
@yegor256 , review the pull request, please.
=> Migrate to  asto version 0.2

README.md, pom.xml, src/main/java/com/artipie/goproxy/Goproxy.java, src/main/java/com/artipie/goproxy/package-info.java, src/test/java/com/artipie/goproxy/GoproxyITCase.java, src/test/java/com/artipie/goproxy/package-info.java
=> Domain name changes: yegor256 -> artipie 

pom.xml, src/main/java/com/artipie/goproxy/Goproxy.java, src/main/java/com/artipie/goproxy/package-info.java, src/test/java/com/artipie/goproxy/GoproxyITCase.java, src/test/java/com/artipie/goproxy/package-info.java
=> migrate adapter to asto-0.15 version

.github/workflows/maven.yml
=> Add test runs on JDK 11, 13

src/main/java/com/artipie/goproxy/Goproxy.java, src/test/java/com/artipie/goproxy/GenerateVersionJsonTest.java, src/test/java/com/artipie/goproxy/GoproxyTest.java
=> fix hardcoded timestamp in the info-file issue

LICENSE.txt, pom.xml, src/main/java/com/artipie/goproxy/Goproxy.java, src/main/java/com/artipie/goproxy/package-info.java, src/test/java/com/artipie/goproxy/GoproxyITCase.java, src/test/java/com/artipie/goproxy/GoproxyTest.java, src/test/java/com/artipie/goproxy/package-info.java
#7 Updated year and name of license header.
=> #7 License header update

README.md
For #20 added docs for go module proxy protocol and todo for next steps.
=> #20 API for go: added docs

.github/workflows/maven.yml, pom.xml
For #26 I've set up jacoco plugin and coverage report upload to codecov.
=> #26 test code coverage

README.md
I've corrected repository structure in readme to correspond actual result of `Goproxy` work.
=> Readme corrected

pom.xml, src/main/java/com/artipie/http/GoSlice.java, src/main/java/com/artipie/http/LatestSlice.java, src/test/java/com/artipie/http/GoSliceITCase.java, src/test/java/com/artipie/http/LatestSliceTest.java
For #33 I've implemented `LatestSlice` and upgraded artipie-http version.
=> #33 Latest slice

src/main/java/com/artipie/http/LatestSlice.java, src/test/java/com/artipie/http/LatestSliceTest.java
=> #39 - Latest replacement using path uri

src/test/java/com/artipie/http/GoSliceTest.java
Created test for `GoSlice` for #42.
=> For #42: test for GoSlice

.github/workflows/codecov.yml, .github/workflows/maven.yml, README.md
#44 - upload coverage to codecov action
=> Upload coverage to codecov action

src/main/java/com/artipie/http/GoSlice.java
=> Removed puzzle for #42

pom.xml, src/main/java/com/artipie/http/GoSlice.java, src/test/java/com/artipie/http/GoSliceITCase.java
=> Update http version to 0.15.7

pom.xml
Removed unused dependencies from pom.xml.
=> Pom clean up

pom.xml, src/main/java/com/artipie/http/GoSlice.java, src/test/java/com/artipie/http/GoSliceITCase.java
As a part of #62 I've added auth to `GoSlice`.
=> #62 - Authorization added

pom.xml, src/test/java/com/artipie/http/GoSliceTest.java
Closes #62 
Added authorization to `GoSliceTest`.
=> #62 - test for authorization

pom.xml, src/main/java/com/artipie/http/GoSlice.java
Updated http to `0.16.1` and used permission actions.
=> Updated http to 0.16.1

pom.xml, src/test/java/com/artipie/goproxy/GoproxyITCase.java, src/test/java/com/artipie/http/GoSliceITCase.java
Closes #77 
Update testcontainers to fix the build
=> Fix build by updating testcontainers
